/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.EventQueue;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class RegisterForm extends javax.swing.JFrame {
    User user;
    /**
     * Creates new form register
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regis_button = new javax.swing.JButton();
        regis_lbusername = new javax.swing.JLabel();
        regis_txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        regis_txtPass = new javax.swing.JTextField();
        regis_lbfullname = new javax.swing.JLabel();
        regis_txtfullname = new javax.swing.JTextField();
        regis_lbtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regis_btnnavigateTologin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("registrationForm");

        regis_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regis_button.setText("Register");
        regis_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regis_buttonActionPerformed(evt);
            }
        });

        regis_lbusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regis_lbusername.setText("Username");

        regis_txtusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");

        regis_txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        regis_lbfullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regis_lbfullname.setText("Full name");

        regis_txtfullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        regis_lbtitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        regis_lbtitle.setText("Registration Form");

        jLabel1.setText("Already have an account ?!");

        regis_btnnavigateTologin.setText("Login");
        regis_btnnavigateTologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regis_btnnavigateTologinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(regis_lbusername, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regis_txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                                .addComponent(regis_txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regis_lbfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(regis_txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(regis_lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regis_btnnavigateTologin)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(regis_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(regis_lbtitle)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regis_lbusername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regis_txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regis_txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regis_lbfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regis_txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(regis_btnnavigateTologin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regis_button)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regis_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regis_buttonActionPerformed
        // TODO add your handling code here:
        String username = regis_txtusername.getText();
        String password = regis_txtPass.getText();
        String fullname = regis_txtfullname.getText();
        
        if(username.isEmpty() || password.isEmpty() || fullname.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "username/password/Your full name cannot be empty.");
            return;
        }
        register(username, password, fullname);
        JOptionPane.showMessageDialog(rootPane,"Register Successfully!");
            
    }//GEN-LAST:event_regis_buttonActionPerformed

    private void regis_btnnavigateTologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regis_btnnavigateTologinActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginForm loginform = new loginForm();
                loginform.setVisible(true);
                setVisible(false);
               
            }
            
        });
    }//GEN-LAST:event_regis_btnnavigateTologinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton regis_btnnavigateTologin;
    private javax.swing.JButton regis_button;
    private javax.swing.JLabel regis_lbfullname;
    private javax.swing.JLabel regis_lbtitle;
    private javax.swing.JLabel regis_lbusername;
    private javax.swing.JTextField regis_txtPass;
    private javax.swing.JTextField regis_txtfullname;
    private javax.swing.JTextField regis_txtusername;
    // End of variables declaration//GEN-END:variables

    private static String register(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) {
        components.MyBankWS_Service service = new components.MyBankWS_Service();
        components.MyBankWS port = service.getMyBankWSPort();
        return port.register(arg0, arg1, arg2);
    }

  
}
